; generated by SuperSlicer 2.4 on 2024-06-11 at 10:45:08 UTC


;
; thumbnail begin 32x32 892
; iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACYklEQVR4AZ2WMWpcQRBE5yQ6iFl0AG
; XG4MixWUfG6SYGB/IF9gCKFhQLwca6gUAX0Ekk+kN9at9WjxYFw/7f23+6q7u6ZsZ2u32tdTgcHvf7
; /ZMv/VfPm83mTe/17D7+69+5zddut3uR39BmnkDZ3K6gtepdvrIJgPt5cL7Ld0mgQ84KpA35P1F3fh
; 5rEI2QOxqvEKvxGZuSKPvwrDwZcsM/TLzwIO5Xdm8LuTIc5SVoRKKOkOSF2x3k7Z8fi22IkR1qZp4C
; JKKlcsvv+ddYvx9OEkeTMqdfVyH38wnhnmsLZpnPSksb+51QK3H5jSQgiXD0S2ho0/u/nzfR70QHPk
; J4PB7v07h239bz7berVqjWMUyZJwFhHyk+rNDd7+vXVN3pGBbKJLsp8zSunTwn3zMOpL6nzDvUTrS0
; ZydUoxOfZE/jJb/vX66mUtwdViNJJMdwJlSFmvIsXz92E5/WFnT9SuN5QrSvoz2sZqPtCQ+WxzNPY6
; jxYsUuqZrHqP2WMWTPO1GRX5WchKWfl5zyzCRPlFBjmAJ/dFhdIs/1rErKd/AA0vKecryIngiT7PLm
; tZKQvVFwVUP9nslzIi6FK92KFg6kMaznh783J5dI9xNJO95QfIjcR3ZQgDReScE6oUksZ2BWeG1BEg
; ui8kqwGgzgJPN9efPSfqsUP/+/PrsHsK+zaqSydzLu8ry0oHScpUktYDW4GVGrNUmezzjA8SApU1Jp
; JQ2Z2S6+ETlz1WvvN/lDee7ixBtRh4a9ZgIkNCvLPev5bAwTaopHOj/SoZb2JH/irZi21PeEUotCRd
; QO7B10EdlUd2E8jQAAAABJRU5ErkJggg==
; thumbnail end
;

;
; thumbnail begin 400x400 17240
; iVBORw0KGgoAAAANSUhEUgAAAZAAAAGQCAYAAACAvzbMAAAySElEQVR4Ae2dPa4syXGFayVchyA8CD
; JkjScIkHwZxMiTPQ4BGZIjkwuQ1cAD5BEPuLZ2IIAbmJVQag6Kky9vVlX+RESeiDhGgsOZrp84+WWc
; ioq83ceXL1/+NDJ+/PHHn3//+9//z/t/R49FGu8YyjESfzkQYxvVYfSYKAyUHIzGTwbyMnDOe5k/Iu
; TD0WPeMR+zF/S6eOqJnxGuPI9XcFZi985AzcHqOchATgYimMgqA9MGcgroCSAJ46jjP8HxBI9E7F4Z
; KDmQip8M5GWgZSKe8uHqOY7VE3iAR6rqeDo/OjjnfWqc18vC0Zh/MkAGPFUjkgwcEic5bwpRtNo4tO
; 4RPYFY3BtyAtEyDjLQZgA5F2jGjm4i0vclZiClgCjCaVYdV/EjJhGL2FEZKDmwip8M4JnIjhyAZiQa
; 8R/SJyxF1Dh3r1A7JxAlgVgmTjQGds8DGcjNAJKJaDKgYiA7J8666uiJfwc8O2PfzUDJgfV1yQAZqG
; Pf2WDXjv/QPPkpooVo2o3y1fuyAkerSeqBgZoDi+uRATIwcj9WHFgxoG4gZzCaACEaR2sytcFBeGWy
; i4GSA+1YyAAZmJ1/CxOxZMDEQE4BNeBBN49aA63JRY9dk4GSA6tYyAAZmI1d00is4z8sL1aKKCGUdV
; koFb/k/XpJnBoMlPF7mX8yQAY0TGQXA+YGUgo4K5ynquMqfoknMY+xSzFQcrA7FjJABmZjlzCSnfEf
; uy58ijgiGmqjfCX+GXAixD7LQM0BShxkgAyszP+MiSDEv9VATgF7AIpkHHX8I+BEin2UgZID1FjIAB
; mYnf+R7b4o8W83kFPAO9GimketwV0SQdyaaclAyQF6LGSADKzM/101gsYAhIGU4pSiSb0j9DKuEkiG
; 2K8YKDnIoAEZyM3AnYkgxg9lIKWAr9frW/Sq4yr+Molkir1mIFKvgwyQgZn5P8c7HyLeK5yB1FVHxs
; Vz6vDx8fE1y1NnPbKaR83AO3FkZuB8kPR035Lxlw/TiBxAGUjrldXMDg3v41ww5VNYJg1K45jdpUQG
; yEAEDWYa7JYDpol+VXVkMpGr1xWZFtBV1UEGyEBmBnoa7DvGdgPpfV0V3UieoIieQHpeV5EBMpCZAU
; QT2WogveZRChgRnp7Yy/ijJZHe+ScDZCA7A60G+04dthjI6vbcKPCMLJo6/ggJZGUBkAEykJkBFBMx
; N5DRquNJQK8ArcR+xu/5SWx1/skAGcjOAEKD3fTr3KXMoz6vJ3iumqSr5/Oigcb2XDJABjIzsLMaMT
; EQDeOoBfQAkNbkekkgWvNPBshAdgZ2VSPqBqJtHqWAqPBIP3E+XQdRA+35JwNkIDsDOxrsagay2ihf
; FdHiWr06WN4PWgLZUVaTATKQmQFLE1ExEKuq40nA3QDtiP2MH+FJbNf8kwGc7b5kYA8DVtWIqIFoNc
; pXRbS+LkLs5XxYa4D0BEwG9jKAokFWBrRNRMxAkIyjFtASIKTYz/gtm2po808GyEB2BjQb7MsGglZ1
; XN2jNjxWTdLV+9PUAHX+yQAZIAM61ciSgexqlK8IqAGQh9jP+DXuFTlpkAEyQAY+z79Uzp42EPSq40
; 5ASXg8xV7GLwW7t/knA2QgOwOSDfZhA/FWdTyJOHu8x0VTx78yfxavQ8gAGSAD+vO/ksuPEQG9Vh1P
; Ao4KFyH2Ov4RDaLMPxkgA9kZWGmwvz9/9IjnoVG+KmKPaOhN0pX4exYQ0tZMMkAGyID8/PdUI+Vnjy
; d4IhtHC54r4byX6r0A3cUfef7JABnIzkBPNVIzcNwBlMU87uCJ+sT5BFGpQZb5v2Lg1MBLDGSADKzG
; 3qpGWgwcrRN8fHx8fb1e33rKmegiZov9jP8d+8lAVg0iv64hA2SgZ/5PBt6jxcAnAymhyQrOe2ReOH
; X81IDxUwM+SLZ0OOoP16VLNvHqp41si6d+4iIDZIAM5GbgrsF+lGK1SrVM8FyVqU+NtUjxtzSY3epJ
; BsgAGYjBwFWD/bgzjyuAkIOfGT2N8ujwPM0/GSADZIAM1EZyjPQ6IsIzGk80eHqSBhkgA2QgBwMjPv
; AXAxm5UKQdSqOx1wJGiH9GAzJABshAbgb+8gpr9qKexZtdNFci7ohh9b4l5o4MkAEykJuBQ+oGvAgo
; AYz0JFjHL6kBGSADZCAvAyK/SOhBvJ4G2er50eGRThxkgAyQgdwMiP2kLTI8VveFukNDM2mQATJABv
; IycEieDLGxZrFoWhogxW+pARkgA2QgDwOH9AlP8XbDY71oWhogxL/rHsgAGSAD8RlQMZBSuB0C7gSm
; 1mDHAtq9aMgAGSADORg4NE9uLR7KomlpYPXuFVEDMkAGLBnQbpSTgV+HuoGUAWmKhwhMrYEmQKiJkw
; yQAWsGUPoOGRg4rC50iic9wahPG1f3qgEPeuIgA2SADMRkwNRAyomWEA/9aeNOA6n4PWpABsgAGYjB
; gLmBlMKtBO3laeNOg9X4PWtABsgAGfDPwLHrwrPieV80LQ1G4rd4j0wGyAAZIAM9Y6uB1EI8iREJmF
; qD3vgjakAGyAAZ8MnAdgMpxbtyVE8NspX47+CJmjjIABkgA7gM/Ps//Ob2v8MYyCleDU+kUr1XgxKg
; DEmDDJABMoDFwP/+y/GXcWciUAZSCvcW6/V6fUO7P2sNMiUOMvBZg3f8ZIAM7DKPJxOBM5D3OKHJ9t
; RxjpH3wVEHGSAD5wMUGbBh4G0SLfN4j3/9q6N5DJyBlE6bcRHVVcfdO+HIGpABMkAG7Bi4Mo7/+vtr
; 83gPuCb63X+LDM/TK6sMi4cMkAEyYM/AXdVxZx7vAWEgPVBEhqe31/G0Q8O7BmSADJABOwaujOM0j3
; /86988ngPiDwlnjokCUC80ZfyREggZIANkwJ6BlaqjHNsMZGXyI8Cz2hyMkEDIABkgA7YMPDXKR8zj
; PbYYyOjTxp1wHhfR6NPGnQZeFxAZIANkwJaB2Ub53TA1ECnBZsRDGE8NspXzelk8ZIAMkAFbBqSrjn
; KYGYi0WK0JQV5EGsC04EFeQGSADJABWwYkGuV3w+wnbbWvUwNkcT0UaMr4ERcPGSADZMCeAa2qoxyq
; BrJjEpHgsQKmpQHK4iEDZIAM7PseK03zeA81A9mxaL4U8OwGaFfiKDXYvYDIABkgAxjmIW0c5xA3kN
; 2Lphw74EErn3c8iZIBMkAGbK/Z0yjXuBdRA0EB5moitScTadFcaaB9LTJABsgARtVRb8/VYEDEQCwb
; ZBIAaZ3bgwZai4cMkIHsDLyHh1dWkgwsGwhSqb4DHg9Jo9ZAOomQATJABrAa5U/bc6UYWDIQT4umFk
; 4CIG+Jo9ZAYgF5jP/UgAyQAY8MSDXKJRiYMhCvi0YKnjN+L09cdxrMxkAGyAAZsGVA6y/KVxg4RgXw
; DkxLuBEBIyyaWgMyQAbIADYDvY1yawaOUkAkwawBehLPS5N0RQMyQAbIAB4DGlXHCgPlZomjPrB1cF
; RgeuGJvGhqDcgAGSADGAysNsq1GCj//XF3YOk0WUYNUJbEQQbIABnAYcCy6lhh4Lg6+PV6fZttrESA
; 5+Pj4+voO8FoGpABMkAGbBmw/B4rCQaaBnIKlnXxvOM+RcusARkgA2TAjgHtRrkGA0f94bpMGdmZ4H
; 20hMq2gMgAGSADtgxo/uCTNgNHecCdoNEBunvHWcITXYMvZIAMfCEDVgw8VR1ajfIVBkojPXobZJHh
; 6W2QRX0SJQNkgAzYM4BWdfQyUHJwjIoQCaCZnRXREshMLGSADJCBeQZ2bc/VYGDqq0wiwDMDTR2/9y
; QyGz8ZIANkYI4BtKpjlYGlL1P0CM8JjMR9e00gK4uGDJABMjDOgJdG+ehY/jp3TwtIctGU8Xt6EpOO
; nwyQATJwzwDq9lyJ84j9IiHy4jnh1lg49TXQNdC+BhkgA2TgVwY8N8p7huhP2iI+hWkD05octAVkeU
; 9kgAyQgR9/jtIofxqiBoIGjyU0tQYIScTiiZMMkAEy8P2IXnWU49A46XnTu+CRbJCtTtpODRCSFxkg
; A1kYQG2Ua8avZiAnPNYQ73rivIp/x5MYSvxkgAxkYeCpUR6VgUP7AidA2sJZNMhW701bA9T4yQAZiM
; rASNURkQETAynh0RAPedGU8Z/waGlgGQ8ZIAPZGZhplEdj4LC8mAY8HhJHrYHkU8iuJikZIAOZGVjt
; dURh4LC+YAnQyjm8JY3WZEtoYPlOlQyQAQ0GVu4freoYaZRHYGCLgayK5zlxlPGvaoAUDxkgAysaeG
; BAY4eVdwaOnRcvBez9rOcnLomYIiROMkAGPDFgsT3XKwPbDaRXvIiLphX/kwYe4iEDZCAKA0/bc7Xi
; 98IAhIGUAtbCIW/N1Ii/tYC8NUnJABmIwIB21RGBASgDKeHJlDTq+Et4or2uIQNkAJ2Bme25WRmAM5
; BSvGyJo9bg4+Pja7bEQQa+1+D1en3LzMA7/gxVh1cG4AzkTBoruzO8j1KDjE+fZIAMWDOA/INPyAxA
; GUjriTPbAmrFnymRkgEyYM2AZaM8GgNQu7DuStXoi6cn/shJlAyQgR0MoFYdXhjYbiAj77mjPoWNxB
; 8xgZABMmDNAEKjXIKB3RxsNZARaCThQRmz2/IiJREyQAasGYjyg08IDGwxkBlgWuJ5XjyrE+89gZQN
; whUNyAAZ6D1e8nusyMAvw9xAJMwDRbwVDaTi96gBGSAD1gx4aJR7ZMD090C0AvTyJCq5aKy0JQNkwD
; MDyNtzPWl7NUwMREuwFjyoC8gifpTG2k4GkJMoGbBlIHLVgcKAuoFYQFOKh7Z4Zhtkq9dD0sCSgZID
; q+uRATwGojTK0RlQMxBrYGrxEJLIrkWMkkDIABlAMY7d23OjMqBiIDsTRynezgSCEv8ueMkAGchedW
; RgQNRAJLblaQlodT2ExFnHbzknZIAMWDPQ0ygnAzoMiBkImmAW4rU00Dz/SvwWT+NkgAygVB2tRjkZ
; kGdg2UDOSUEVrSWgxnm9xK+xgMgAGdjBwOwrKzIgx8CSgXhJGrV4kgChva7piV/ynskAGfDYKCcDMg
; xMG4jHxFGKtwqPl6eNp/tf0YAMkAHPjXIysM7AMXogYpN0RbyZOCLFPxMLGSAD1gxofo8VGZhn4Bhx
; Yc9PnFLiRYyfDJCBEQ2QG+VkwJaBo0c8rcYbooBPgiHHsBo/GSADPQxYabDje6zIwBgDR+vA8uDogt
; XitADKFD8ZIAMIDDxVHZp/UU4G+hk47g7OlDjK+MuRLX4yQAZ2M2BddZCBeQaau7Ber9e394j8uuJp
; vOOP/srmKX4yQAYsGZDYnksGbBn4ZCDl7ooM771b43Taq1I2Q/xkgAxYMoBQdZCBcQaaPZDyA5kSyF
; WZlgUeMkAGrBnw9INPZODzvz/uBGsdGFXAp3ec0ZMoGSAD1gxYbM8lA7oMHCMNsojijTbIoiXQ0SYp
; GSADEgx4/8EnMvDL54/ZC0UQbzaOKO9ER4AhA2RAgoFIP/hEBv6/Apm9qOckMvq0cXUOz/DMQhOFgV
; OD1fjJQD8DyI1yMjB3/NK38XpMINL36w2ecmeFVPweGVhNHGSgnwFPjXIyMDZEfg/EiwtLAlNr4CGJ
; Si8aMkAGnhjw2CgnA/1D7BcJkcXTWjQtDRDjH22QkQEysHqdDFUHGRD+TXTEBGIBTK0BEkBWi6bFAJ
; IGltfLzgBqo9zyelkYOKRPeIq320gkGuUr10aAxzpxkAEy4H17LhkYGyoGUk7cDvFQqqBd8Ow0DjKQ
; kwHNH3wiA2sMaF5bzUBK4SwnEiFx1hpYx4+kARmIz8CTcZCBuAwc2hewEg8tcbY00Iwfsf9EBmIzMN
; ooJwPxGDAxkDow6eCQgbGYXPRFQwbiMTC7PZcMxMoDh+XFpMXb2SBbvW8peLyYBxmIw4BEr4MMxMgD
; 5gZSTviKeMiva3o1WAHIo3GQAd8MSG/PJQP+88Cx68IrjTXPibOlwUz8ETQgA34Y0NphRQZ854Fj58
; VP8XrhiZI4WxqMxO/5iYsM+GLA6i/KyYDPPLDdQErh7gSMCEytwR0UURcNGcBlYLZRTgbiMPA0IAzk
; TrzoibOlQRn/qUkWDcgABgMWVccIA14b5Z4Z6BlQBlIKlQ2YWoNsxkEG2gy8Xq9vnhvlUgxEe22LzM
; DIgDOQU7hTtIzgvEf2+MmAPQM7q44rBqL2/VAZGB1wBlKKlfHpo14wM7szImhABuwYQP8eKzKAmweg
; DKRVpq1s8/M2rl5ZZVpAZMCWAetGORnAY2BlQBhIz7v+yPD0xha5GiEDtgx4/cEnMoCVB7YbyEhzqB
; Q4CkCjjfKnbY5eNRiJnwysMfBUdaD/4BMZwMkDW/8SfUSw1rHe4RmFpow/wuIhA/YMRPrBJzKwPw9s
; MRCJSfcMzywwLQ28GgkZsGUAZXsuGdjHgMYwNxAJwWrhPAEkBU2tgacFRAZsGUCrOshAnDxgZiDSgt
; XiocOjvZ/dg4lkZ0D7HmsGvDbKUfWVGNYMaA8TA9EC5mpi0ADSXDRXGmhfiwxgM+Ble65G/KhVecQ8
; oP6b6BaC7RKv9152aICyeMhAru+xIgMYDJzX1Y5fzUB2Th4CPDuAqTXYbSRkwPcPPpEBfwy0NNDMA+
; IGsuNp4+lerAHaDU0Z/w4TIQN4P/hEBpgHNOIXNRDE9++W8Gg3ylc0sLonMoD5g09kgHlAgwExA0F5
; 2rgTTnMRoTxt3GmgDTUZwP7BJzLAPCDNwLKBoAumKV55Tk8aSC8eMmDLwOr2XDLAPCDFwJKBeBGrNd
; ESAnoCptZACiAy4LNRTgaYByQYOGYv7FGwVgyz4nmFpox/BR4ygNcon4mfDDAPrDBwjB6o/Q7VWrzR
; eLwD09KADGAzoP2DT2SAeWCWgWNEvEiC1cL1aBANmlIDMoDJgKZxkAEfDFhqMMrAUQuYSbBe8VbLXE
; 8akAEMBnZ9jxUZYB4YYeB4Eig6MFfxnxpkWDRkAIuB0e25ZCAeA0ga3DFwXB38008//TGTYHX8r9fr
; WzZoyMB+BnZUHWTgOv5z/pkH2vE3DaR03+jl2lX8Z/LIGD8ZsGdAansuGfDLAKoGdwwcrQPOf84IT/
; m0MdJYi6YBGfheA00GkKoOMrCHAVQNnhg4rgQrRwZ4zvgzN8/IgC0D3n7wiQwwD9QMHOcBTyeNLF7P
; O87SgaNq8PQZMiDHwO5GORnYzwCqBk+fKRk4RptDkYQrm2Sjx0TRYDR+MrDOgKeqgwzoMIA2ZhmY/i
; oT7wDNCFbGHwGe2fjJwBwDqI3y2WPJAPPA9JcpeoZnBZpaA48AnfctcR4y0McAWtVBBpgHJBg4JG7C
; i3B3DbLVSfCkgfS9koFrBrS/x4oM4DOAqoHEvYr8oJQH8aSeNq7i96KB1rnJwGcGvDbKyYAcA6gaSJ
; 1L9CdtEZ9CLCcUFR7NRUMGPl/rD7/74ecIjXIygH+t3QyIGsgpHgpAloumjL/8603La19pYH3NzAw8
; VR3eGuUrDKAkUeYBPQYOjZMiJJAd0NQa7FxAUk1SMtA/ojbKJTjYdX3mAV0GDq0TnzdvDdBuYFqTZw
; 0PUvmcgYGnRvm//faHn8kA80BEBlQN5BTPCh4kaOr4rQBCiz86Az1VBxlgHojKwGFxkVJALbHQdz5o
; w4O4aCIzMPM9VmSAeSAaA2YGoiWeh0VTxq/xJOYl/igMrGzPJQPMA5EYOKwvWAq4eg5P0LTuXUqDnb
; FkY0CqUU4GmAciMLDFQM6gZwHyCkxr0mfhQS/VozGg8T1WZIB5wDsD2wzkFG8UngjQ1BqMQOD5idMr
; A9rbc8kA84BXBo7dN3CK8SSchwbZSvw9sUWNH5UByx98IgPMAx4ZgDCQJ/GiPW1cxX/3JBY9fjQGVh
; rlZCAGA7vi98QAjIHUAp7/nAGaOv5yAWWLfzcDCD8zSwaYB7wwAGcgp3iv1+tbtkVTxv+O/a1B1NcV
; iAxoNMpXGYj8ygqRAbT40RmANJBStIyLp3z6yJpArBnYXXWQgTYD50MU8wAmA1AG0irTssFTg5ItgV
; gzgFR1kIFnBjJp4IEBGAO5e8eXZQHdxZ9BA2sG0KoOMvDMQAYT8cTAdgMZESQqPL0NsqgJxJoBhEY5
; GdjLAOLwyMBWA+kVDFU8KQ1m44+ggTUDO7bnkgEsBlA1mI1/pwbbvgtrBpr6HJ7hOTVYPd6rBjsYiP
; aDT2SAeWA3A+YGsgpMLZ5HgKQm3GsCsWbAQ6OcDOgygKqBdwZMDUQSmlI8T/BIx39q4CWJWDPgqVFO
; BnQYQNVA+pw7GDAxEIs/hkGHR2PR1PEjJxBrBjw3ysmADAPIGmjGb8mAuoFoC7ZTvBENrOJHfBKzZi
; BCo5wMrGnAPGDDgJqBSDTIVgW0vm49dsaPsICsGchYdZCB+2szD+gyoGIguwSrxdsJEEL8OxOINQOo
; jXLra2Zm4EoD5gG97b7iBoIATSmeNTyr2/K07sdSAxTzOKsOMhCfgaf4yYAOA2IGggRMSzwLeFAbmF
; YJxKJJWo6nqqN8ZUUGYjIwqgEZkL03EQNBNg9N8WoNLOJYiV9TA7SqgwzEZ2BWAzIgp8GSgaA06mYE
; lDqfh0WjOWfWDEg0ysmAbwak7pkMrM/ZMXsCb4LV4kkA5Dl+icYaStUxsz1XagGRAd95gAysMXDMCO
; gZmlK8WeHQGmQrGswuIA+vrEY4mNXOInYyoK8BGRhj4DzmGGl6RQGmFmIEIG+lei8II/FH255LBrAZ
; sNKADIz5wJ8N5DzwyUgiQlOK1wNP9PifAIpSdZABPwzs0IAMPPvAXwzkPPDKREYqlCgCXonmIYbV+F
; tzbc3Azr8oJwMYDOzWgAy0faDm4KgPKj/w/kH7DILdiZcx/nJ4bpSTAZ8MoGhABn4Zpw+0ODiuhHsf
; 9PHx8TXDE0drZFw0dfzWDxC7qg4ygMMAogZZ4z/NozSQ+jPHlWB1NZLJSMqYs8VeMjCzO2NmWDTKyQ
; A2A6gaZGXgygfqzx2tg97/XJevGSBqbcvLBk/rSUMziaBVHWTAngG0kZ2B2jjuGDjKA1riZDGRp9ii
; w/M0v9IJZOR7rMhATAZQNcjKQE/FUTNw9Lzji16N9L7jjLqAehgoOVhdRAiNcjKwxkBUDXo+FzH+q6
; rjiYGhrzKJZiK9i+ZKQIQYVsbsQpg9LtIPPkVjYFSDSEk0MwN1Th/R4X3ssXpBryLOAFPr4Bmg2UVT
; c9CrwVPV4fEHn8jAGAOoGqwc75mBWeMox/S38XqtRloNspVzeYRnNXG09LzTwEOjnAzoMoA2MjOwUn
; XU45C8EXQBte7RC0CSSaPFQR0/8vZcDQ3IgA8TycxAT6N8ZCz/oJSXBrvGomnpgAqPVuJocfD+X7Sq
; gwzYM6AZCxmYn39JDsR+0hbVRLQXTUsHJHisF/QffvcDnHmQAVsGEE0kMwPSVUc5xAzkFA2pwW4JTE
; uH3QBZLxrP23PJgF78CBrsuC4CAxpVRzkO6ROWwu2qRiQbZKv3sQOe2a2ZKyNyo5wMrN/HTg2sr4vA
; gGSj/G6oGEgrACsB0Upn63eiKMZRNsqt54QM7DeOOn4yYMeAhXGc49A8uWWDHeVp404HbXiQqw6rJE
; IGsMyDDNgyYGke73FoX+AUTtNE0J427nTQuE/rKm/2L8o1Ewhy4ozIwEr8ZECeAc1G+d0wMZBTNI0g
; PQDT0kFqgr01ysunMEkNLGInA3LxkwE5BqyrjnIclhcrhVs1EW+LpqXDCjzWTVLp77GSWEBkAKNRvn
; r/ZGAufqtG+d0wN5BW4KMiegam1mEGIMRG+Wz8M/NPBvwnTjKwxsBu4zjHsevCp3Aj1Qhyo3xFgxF4
; kBvlqxz0aEAG4pgHGZhjAMU83mOrgZQwPJnIaqmLPp7gQas6pP+2oyeBkIF4xkEG+hnY1Si/G9sNpB
; TtSpzIi6bWoQVGxKrjiYOWBlbxk4G98ZOBz/EjVR3lgDCQWrhzvF6vb1mgqXW4W0haA+UHn8q4syRO
; FAaQ4icDP/585kBE83gPKAM5RSvNY6a5FmGU8Vtcb3V7rgYHbw2yzv/JwKmBp/uWZCBzDjjzIPKDNK
; yBjDbYI43yScNi8SBUHS0Gah6s7yMTA2gjMwOt7bmoDEAZSA1JNhO5KlFnt3o+Da3tuZIMlBxkSCDW
; DKBqkJWBu9dViAzAGMhVifbUYI8ynt5vSsODVnXcMVBzEDWJWDOAqsFT/NFzwB0HaAxsN5CnRVMKF9
; FERuNZhQelUT7DQMlBpARizQCyBr3xR8wBIxygMLDVQHqBKUXz8F5wJP5RDUodRmNHa5TPMHDGH+Vp
; 3JoBVA1m4o/AQE/VgczAFgOZXTS1cF6rEamtiSOLx3PV8aSjxwSygwFUDSTO4TkHSOTDXfGbG8gqMF
; cT4GUhSSSNWoe72FEb5ZLxe0sg1gygaiB1v94YkDIOBAbMv85d+pyeqhHpxFHrUMeOvD1X69zoScSa
; AbSRnQEN89jJgImBaE8quolY3dcJj/X3WCEwUHKAmECsGdC8BhmYn38LDiwZUDcQraeNK9HQjETrif
; NqRGmUS3CAkkSsGUBMopkZ0Kw6djOgZiDWi6YWbreJWAPsfXuud/0R7wGhGsnMgGSjHJUBFQPZBczV
; xFkvJLSq499++4P5AtrNQMnBjkS6M3HWGuwykswM7DYOKwZEDUSzQbZyP5bVCIp5nFWHdQJBY6C8Jy
; sNUMyjjJ8M2DCAUHVYMiBmIGjvXK8mVOseUYzjanuuRRJBZaDkQDt+tMRJBuwYsGyUozAgYiDIi6YU
; TWty0aqOJx00wEZnoOZAWgN08yADugwgVh0WDCwZiJdFUwonaSLWTxpSjXLJBOKNgZIDCQ2sX49Jak
; AG5HIActWhycC0gXgDphRNosGO1iif1WEFIK8M1PHPauAxcZKB7+NfeRr3VHVoMXCMHojYIFsRbvTJ
; oTzO6l41t+fOLJ4oDJSxjGiwgwFtDcjAXA6IwsEsA8eIA3ss1UdAeNIBvVG+Ck9GBkoOeuOPkjjJwD
; gD0YxjlYGj58BITxtXoj1VI5Gqjhl4IjNQx3ilQVTzIAN9DEQ2j14GTh3Ofz5aB9cfjva0cQdObSJ3
; pqIxdv9FeWYGSg7KeK0ZQNCADHzOAZk4uGKgNs7jTrzoTxtXop1CfXx8fH29Xt+sri/dKF/RISsDJQ
; fReh1kYJyB9/qPXnWsMNDchZXtiesq/reBWOiA/D1WWRkok0f2dZAx/jNplgbi6f6tGDhaB5QiznTn
; owg20mCfHVaN8lENyMAvGpRPYdk0yMpA65UVGWgzcJQfaLlsJnhaTxo9DfbZ4eUHn7IzUGoTXYPsDN
; w1ysnAZwaOU7QnUSLD81SiSpuI1x98ysxAyUFkDbIy0NsoJwPfG8kx8m4voni97zfrpuqsDmjGcWpA
; Bvo0KDmIpkHvZ6PFf1d1kIF7Daa+yiTCU8gsALMmEu0HnzIzsHos0sjMQG0cozqQgYXvwvIs3opgZe
; y9DXaU7bm1BqvnyMxAHb9XDVbP4ZWBFeMgA7+O5a9z9yRcmfilz3e1iLw0ysnA+jm9aSB9Tg/x12tW
; OhdkY+CQuhl0gKSTRj0RtYmgbs/VmqPMDJQcoCeQzAxoGEd2BsR+kRAZHs3EUcZ+Xsd7o5wMrGmAmk
; QyM6BtHlkZEP1N9FM8FOHuXi1pjD/87oefIzXKycB8/EgJJDMDvdtzycDcEDcQFPGsF81do/w/f/s3
; W3SwThrZGajjR3gaz8yAZdWRlYFD68SlgJrXaF0TxTzOqsN6Ee1MnFkZeLoXaw0yM6DVKCcDn4eqgZ
; ziWQGEYhxlo3xku6+UBlbxk4H++C0TSGYGkIwjAwOHxUUs4EGrOr404NF8D6uxNZMM6MyR5i6ozAyg
; mkdkBg6rC53BSQunmZRbY/Z7rDRNZEd5nJmB1fg17jUzA7sa5WTA2ECkxUNqlPfssKq3+0rogPzEGZ
; EBqfilNdgZz04GPFQdkRk4dly0FHD2WEu3lf4eKwkT8Zg4PTOgFf9KDJkZQGuUZ2Vgm4Gc4o0C5K3q
; eAJnpsHuPWl4Y0A7/tH5j8jASBKNYBxRGDh238BIAkFulK/C01ONoDdJIzJgqUFPEo3KQMnBU+yRzM
; M7A9sNpBTlCiDE7bnSsT+ZyEqZ62UgMbAr/rt5zsyAt0Z5FgZgDOQUr4YnYtVxF3trkURPnGgMIMRf
; J4rMDESuOrwzAGUgpYCv1+ub50b5SuznQvn4+Pj61sHiumQAL/5MSbM13vN/MpCRAw8MQBqIdamq1S
; iXAme0uRZhZHhd0aPBSH8o4vxnfojwwADcK6zabbWFQ6g6WhrUemRZRDsYQNWg/v/Z5r/kgAxgMgBj
; IHdlmoYDWzfKezWoY8xUjVgzgKpBK8YMJvLU6yADeAxAGEjPOz5JeJCrjrvYI1cj1gygjScG6s9Fnf
; 8nDsgAFgNbDWQmGa7AM/s9Vtoa9MYT0USsGUDVYDT+aPM/ygEZwGBgm4H0PHFKiofWKD81mIk9ipFY
; M4CqwWz83p/Ge6sOMoDLwLYvU5wVrSXg3WdQtufWwKzG79lErBlAHJLxe55/qbVABvYwYGogUoLV4l
; 0B9FR17GqUS8burcFuzQCqBtLxe5t/aQ7IwB4GzAxEI3GU4tXCeWuUS5wbvRqxZgBtaDJQnh99/rU4
; IAP2DKgbiGbSaInnZXuuFjiIJmLNAGISsZoTRBOZbZSTAXwGVA3EMnG8B1rVcWpgdS3EBrs1A6UOKA
; lkV/xI82/NARmwYUDFQKzhjdooX9V/p4kgJLDdCWQnA7vnoDaOnWuBDOgxIG4gKFXH2SjfsYB2AlOD
; s6PBvnvRtHTIyEAdv/X8o3BABvQYEDMQya2ZvaO36rBaPNoNstV50V5EOxgYubesDJT3ZTX/iByQAX
; kGRAwExTjuGuXa70R3v67pAUfTRFCNgwx85kBz/tE5IAOyDCwbCGrVcSWeBjzoibOMXcNIPJgHGfhe
; A43598IBGZBjYNpALF6JlEOyUS4Fj6fEWYMjMX/WDEjrkJWBkgOJ+ffKARlYZ+CYORitUb5DPI/A1L
; GvLH6vi4YMfB//7NO4t6qDDMgz8B7HiHjWTVKL7bmjwkVInK357OXAmgErHbIyUM7p6PxHWwtkYNwL
; jt4DPTTKV+Hp0cAqfmtwerb7Rls0ZOAzBz3zH5UDMtC33bec/6N18N0BFkO76hiFB3VbngY8V9VIZP
; MgA5/jvJr/6ByQgTEvOO4ORKs6LP6ivIZnpKyLAk5pIhmMgwy0OZDolZEB/wyc8bc0OK6Ee71e36JX
; HU/iZUuc5fy/Y38z8PHx8TXTwiEDv8b/nv8zD2RdC9kZePKC40q00abK7ED+HqvRxlokcE4DyfbkSQ
; ba32OVcR0wDzx7wdESrHUCDQE1tudKQHMl4o772RH/qcFIgz2aBlkZaPU6tPMAGcDloBV/qcFxdYC2
; eN5+8CnD4rli4KnBHmVkZqBne26GJMo8MOYFR+87Pil4LLfnjgjWE1fvNr9IwNTzH9VEMjPwZBwtDi
; ImUeaBcS84eg6ohZsFCK3qOEUb+Xw0eHqhqec/kpFkZmDEPFocRFoHI5/PnAfK+Ke+C2sUnog/+OQd
; nhUDiGIimRmQaJJHMBHmgbU1PP1liqUD313cQ6N8RQOPC2h10ZSxe22wZ2Zgpuq4i9/r0zjzwPr8L3
; +d+5143hrlK+f1AE+Z9DXO6WERZWagp1G+em5P60DjvNnywCF5Q6d4nhvlq/CgAiSdMFrzj16NZGZA
; yzhaHCAnUeYB2fkX/U30t2hZqo6rayHCo5k06tgRq5HsDFiYR0tvJA2YB3TygJiBIHyPVUuwHZOIAs
; +ORI5mIpkZkGiUr3KAsg6YB3Q0EDGQyI3y2bF7AVk9bV7FjmAkmRmwrjqeONi5DnZcF4GBkgOt8y8Z
; SM/2XGvxdi6YK4CyPvntMpHMDGg2ylfviXlgz5sAzetMG8hT1XE2ykt4tAVEAqYFj0X8aBpYN9gzM4
; BmHC0OmAdi5YEpA5npdWg+hVg2yFbuURMexKTRmiOtaiQzA4hVx9O9Mg/EyANDBrK6PVcDHpTXNbsA
; Qk8YrfmXNpHMDOxslK9ywDzgPw90G4jUDivJxpqXxHmlgUT83jSQbrBnZsBL1fHEAfOA3zzwaCBa32
; O1Ao/HBXOlwUz8mq8BLGNfMZHMDHisOp44YB7wmQduDUR7e+5MYy0CMCsQRFk0ZeyjDfbMDHiuOnri
; Zx7wlQcuDUSj6lgRz0ODbFWDnvgjatBbjWRmwFOjfJUD5gE/eaBpIP/9T/ONcg14vJfpo/DUsUZNGK
; 35vzKRzAxEN44WB8wDPvJA00D++W9/82cTOY3E8qtI6nI2+oJpxV/CkyFp1LHXRpKZgUzmUWtQGgbz
; AOb8X77CepvIf/zdnu+xeov2er2+ZYOmHGf8GZ64WvP/jv2twcfHx9eMGpzxk4NfdPB035LjZAB1/m
; +b6G8T2XFTZQUy0liLMuqn76wJNNJuI8Y+pwPzAHYeOL58+fInlNEq0zIl0asGWabFU8ff22CPNv8t
; HbIyUGrDPIAVP4yB3L2uygDP0zvODE9hV/HPbvf1OP93HGRmoOQgsgbe8sB2AxlpkkY1kidoyvgjLp
; 5eBqJWIz3mQQY+f5Z5YH/8Ww1kBoJI8PQC09IgUvIciSWSiaz0OTIzUHIQKQ/MaLA7/m0GMpM4a+E8
; AzRrHqUGERLobOzejWSk6iADzxwwD+yJ39xAVgVDEg/hnj0+iUox4NFEWjusJHTIykDJAfOAffymBi
; IFzNVEoAMkuWiuNLCIA4kBTw12aeMgA+34mQfs4jcxkJEGmSfxRoYWNLUGqPFrM4BcjdxtzyUDOtdg
; HrCJX91ALCcTER4LYGoN0JKI1ZwgmoiVcZCBzxwwD+gzoGogloLVwiEAZA1NrQFKAt0RO4KR7DAPMv
; CZA+YBvfhVDGSXYLV4u+BBeQLemUB2M7DTRFa255IBHQ6YB3TuQdxAdgPTEs5yESEsmlqDHQnU6lo9
; sVsm851VBxm4jp95QIcBMQNBE8xCvNY1kDWwSp6a11idGy0OLBvlyAxYNMpX7415QC5+EQNBFas1sR
; rwIANTa6CVRNDj19zui24clgwg9Fx6OGAekGFgyUCQnzae7lk6eeyIZTZ+yQTijQHpasSTeZCBz/fM
; PLAW/7SBeHjauBNv9f41X4dYaSCRPD3GL2EiSI1yMrDGAfPA/L0fs4vHMkhN4WYm39vTxp0GKwkUJY
; 7V+R9NAh6rDjLwzAHzwDgDx4gDRRFsVjyLJtwuDbIyMGIiHhrlZGCNA+aBMQaO8sC7g6MBcwXElQYR
; F02tQVYGehrsUY2DDHzmgHmgn4Hj6UCPDbIV8VpPFtGhIQPfx1kbSQbzIAOfY2UeeGbguDs4YpnWI9
; 4ZdxZgyMDn+X+Pj4+PrzM9EjIQhwPmgXsGjifx0IPUEu71en3LrkHW+M/5Lw0kqw7MA8wDd/F/MpDS
; bUeaKlFG6/VFVg0yMlBWHGfyyGgi2fNA3Q9hHmgzcNQH3AmJGqiGYK34s2iQlYFWr6OnwU4GYnJQx9
; /TYM7GwFH+h7sTRhau5z1n9AWUmYGeRnnLSLzERwbGOXj6DPPAL/EfI2JEdOAnYFriRoMnMwNPxtGa
; /4jVCPMA88AMA8NfZRIJnhFoag0iANTztBGZgRHzqGOPUo1kZ6DkYFa7KBrMxD/9XVie4ZFY+N7hkb
; h3rwzUxjETQwQTycxAyUH2PDBjHucQ+TZeT+KtClbH7/FJTCp+jwzMVB1P8+/RSDIzUHIgFX/WPCDy
; eyAehOtpkK2eG10Drfg9MNDTKJc6N7IOmRmo50rr3JnygNgvEiI7sOaiKeNHbqxqx4/MgJZxtOYfuc
; GemYGSA+34M+UB0d9ER4THAppaA6SnkNkmaRQGLMyjpTdSNZKdgZIDSw0y5IFD+oTnze4WzhqY1mQh
; aLDrHnYzINEoX51/BBPJzEDJwa74o+cBFQPZLd5OaMr4d2tgfU0UBqyrjqf532UkmRkoObC+7hUHEf
; PAoXnyUkDt65zXQiobd9wTwqLZxUBtHEgJ1NJEMjNQas48oM+AuoFYiYe4aFrxa2tgEQ8iA2jG0Yrd
; osGemYGSA+1YVuOPkgcOqwudAkoLp7ktTyN+jQVk3SRFYkBze67W/GtUI5kZOAfzgD0DpgZyBikFkB
; dgWpMsBQ9aqW7JgBfjaM2/pIlkZqDkYFcsKxx4zwPmBnKKtwqPR2jq+Fcn3Wv8Egx4NI/W/K8aSWYG
; Sg52x7Kigec8cOy68CneqHAa5f/O+Gdi8b5oVhjYuT1Xa/5nYsnMQBk/88BeBrYayKh4kRZNGf/Ik1
; i0+EcY8Fx1PMU+YiSZGSg5QI1lNn6PeWC7gdQCXv23iNC0YrzSIHr8dwx4apSvzv+diWRmoNYIPY5V
; DrzkARgDOcWrAcqwaMr4W/Bkib/FQHTjaM1/a7tvZgZKDjzFscqBhzwAZSCneHWTEe0eLTR4x/3TTz
; /9MWv87/F6vb5lMY/W/J/jrYOn+5dkgHngFyNBjR/OQN4jY9JoafBOHBGahCvz3/tePNo4k8Zpolk5
; OOP3dN8aGqDOP5yBlMYhscXN4yjjz6ZByzyyMiC53dcrB+9/Zh7AzQNQTfQrgXp3JngfV1VXhgVUG0
; etQ2YGMpkI84CvPABhID2vq0a2uHkcPfHXjdVIsfe8tszMwF2DPRoHd5+J/jDlLQ9sN5AeaErxoi2c
; 0QZZpAU0sz03OwNRq5GRPFBygBSDFQPl53drsM1ARoGpxYsA0CwAEUxk1DjIwOf5j2AizAO+88AWA1
; mBphTPMzxS8XtMIKvmQQZkv09rNwcr52Ae2JsHTA1EA3Rv8Egsmjp+L8lDa3tuZgY8mgjzQJw8YGYg
; 0oIhiDejgVb86E9iUlUHGbiO3UODnXkgVh4w+UlbTWhaAmpfZ1YDq+sgaTDTKCcDMlqjcmBxLeYBm/
; lXNRArYGrxkACyXshIJmJpHGTg+/lHqkaYB+LmATUD2QFNKd5ueKyeNp6uv0uDXeZBBrAa7MwDsfOA
; uIEglc+74EGK3/petBrlZGB+/nfMBfNAjjwgaiA7nzZ2iHelgcV1RuK3ehLbXXWQgev5tzQS5gHcPC
; CtgYiB7H5dMiKg1vkRF43VHFk3ysnA+hxpc2AZGxkYnyMpDZYNBF2wWjwNgDzFL91Y9WAcZOD7+ddo
; sDMP5MwDSwbiCZpSPCl4djfIVu97RQMvVQcZeJ67VR2YB/Lmgf8Di4VUoMH2+okAAAAASUVORK5CYI
; I=
; thumbnail end
;
; 

; external perimeters extrusion width = 0.42mm
; perimeters extrusion width = 0.44mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

; object:{"name":"Control Validation","id":"Control Validation.stl id:0 copy 0","object_center":[67.500000,67.500000,0.000000],"boundingbox_center":[67.500000,67.500000,0.100000],"boundingbox_size":[60.000000,0.500000,0.200000]}
; plater:{"center":[67.500000,67.500000,0.000000],"boundingbox_center":[67.500000,67.500000,0.100000],"boundingbox_size":[60.000000,0.500000,0.200000]}

M73 P0 R0
M204 P1250 T1500 ; sets acceleration (P, T), mm/sec^2
;TYPE:Custom
SET_PRINT_STATS_INFO TOTAL_LAYER=1
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.10.1 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
;M104 S0 ; set extruder temp
;M140 S0 ; set bed temp
;M190 S0 ; wait for bed temp
;M109 S0 ; wait for extruder temp
G28 W ; home all without mesh bed level
; G80 ; mesh bed leveling
;G1 Z0.2 F720
;G1 Y-3 F1000 ; go outside print area
;G92 E0
;G1 X60 E9 F1000 ; intro line
;G1 X100 E12.5 F1000 ; intro line
;G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.

M107
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0
;_TOOLCHANGE 0
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 Z0.4 F720
;AFTER_LAYER_CHANGE
;0.2
SET_PRINT_STATS_INFO CURRENT_LAYER=1
G1 Z0.6
; printing object Control Validation.stl id:0 copy 0
M204 S800
M73 P75 R0
G1 X97.5 Y67.5 F10800
G1 Z0.2 F720
;TYPE:Thin wall
;WIDTH:0.186364
M73 P79 R0
G1 F900
G1 X97.407 Y67.5 E0.01363
;WIDTH:0.437273
G1 X97.36 Y67.5 E0.01873
;WIDTH:0.5
;G1 X67.64 Y67.5 E14
G1 X96.37 Y67.5 E0.47
G1 X95.38 Y67.5 E0.47
G1 X94.39 Y67.5 E0.47
G1 X93.40 Y67.5 E0.47
G1 X92.41 Y67.5 E0.47
G1 X91.42 Y67.5 E0.47
G1 X90.43 Y67.5 E0.47
G1 X89.43 Y67.5 E0.47
G1 X88.44 Y67.5 E0.47
G1 X87.45 Y67.5 E0.47
G1 X86.46 Y67.5 E0.47
G1 X85.47 Y67.5 E0.47
G1 X84.48 Y67.5 E0.47
G1 X83.49 Y67.5 E0.47
G1 X82.50 Y67.5 E0.47
G1 X81.51 Y67.5 E0.47
G1 X80.52 Y67.5 E0.47
G1 X79.53 Y67.5 E0.47
G1 X78.54 Y67.5 E0.47
G1 X77.55 Y67.5 E0.47
G1 X76.56 Y67.5 E0.47
G1 X75.57 Y67.5 E0.47
G1 X74.57 Y67.5 E0.47
G1 X73.58 Y67.5 E0.47
G1 X72.59 Y67.5 E0.47
G1 X71.60 Y67.5 E0.47
G1 X70.61 Y67.5 E0.47
G1 X69.62 Y67.5 E0.47
G1 X68.63 Y67.5 E0.47
G1 X67.64 Y67.5 E0.47
;under
;G1 X37.64 Y67.5 E4
G1 X67.64 Y67.5 E0.13
G1 X66.64 Y67.5 E0.13
G1 X65.64 Y67.5 E0.13
G1 X64.64 Y67.5 E0.13
G1 X63.64 Y67.5 E0.13
G1 X62.64 Y67.5 E0.13
G1 X61.64 Y67.5 E0.13
G1 X60.64 Y67.5 E0.13
G1 X59.64 Y67.5 E0.13
G1 X58.64 Y67.5 E0.13
G1 X57.64 Y67.5 E0.13
G1 X56.64 Y67.5 E0.13
G1 X55.64 Y67.5 E0.13
G1 X54.64 Y67.5 E0.13
G1 X53.64 Y67.5 E0.13
G1 X52.64 Y67.5 E0.13
G1 X51.64 Y67.5 E0.13
G1 X50.64 Y67.5 E0.13
G1 X49.64 Y67.5 E0.13
G1 X48.64 Y67.5 E0.13
G1 X47.64 Y67.5 E0.13
G1 X46.64 Y67.5 E0.13
G1 X45.64 Y67.5 E0.13
G1 X44.64 Y67.5 E0.13
G1 X43.64 Y67.5 E0.13
G1 X42.64 Y67.5 E0.13
G1 X41.64 Y67.5 E0.13
G1 X40.64 Y67.5 E0.13
G1 X39.64 Y67.5 E0.13
G1 X38.64 Y67.5 E0.13
G1 X37.64 Y67.5 E0.13
;WIDTH:0.353636
G1 X37.547 Y67.5 E0.02951
;WIDTH:0.102727
M73 P94 R0
G1 X37.5 Y67.5 E0.00284
M204 S1000
G1 Z0.6 F720
; stop printing object Control Validation.stl id:0 copy 0
M107
;TYPE:Custom
; Filament-specific end gcode
; total layers count = 1
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA

;M104 S0 ; turn off temperature
;M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z5.2 ; Move print head up
G1 X0 Y100 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 27.84
; filament used [cm3] = 0.01
; filament used [g] = 0.01
; filament cost = 0.00
; total filament used [g] = 0.01
; total filament cost = 0.00
; total layers count = 1
; estimated printing time (normal mode) = 26s

; SuperSlicer_config = begin
; allow_empty_layers = 0
; avoid_crossing_not_first_layer = 1
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,135x0,135x135,0x135
; bed_temperature = 0
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 95%
; bridge_internal_acceleration = 0
; bridge_internal_fan_speed = -1
; bridge_overlap = 75%
; bridge_overlap_min = 60%
; bridge_speed = 25
; bridge_speed_internal = 150%
; bridge_type = flow
; bridged_infill_margin = 200%
; brim_acceleration = 0
; brim_ears = 0
; brim_ears_detection_length = 1
; brim_ears_max_angle = 125
; brim_ears_pattern = concentric
; brim_inside_holes = 0
; brim_separation = 0.1
; brim_speed = 50%
; brim_width = 0
; brim_width_interior = 0
; chamber_temperature = 0
; clip_multipart_objects = 1
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; complete_objects_one_brim = 0
; complete_objects_one_skirt = 0
; complete_objects_sort = object
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; curve_smoothing_angle_concave = 0
; curve_smoothing_angle_convex = 0
; curve_smoothing_cutoff_dist = 2
; curve_smoothing_precision = 0
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; default_speed = 100
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = ; total layers count = [total_layer_count]\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\n;M104 S0 ; turn off temperature\n;M140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+5, max_print_height)}{endif} ; Move print head up\nG1 X0 Y100 F3000 ; home X axis\nM84 ; disable motors
; enforce_full_fill_volume = 1
; enforce_retract_first_layer = 1
; ensure_vertical_shell_thickness = 1
; exact_last_layer_height = 0
; external_infill_margin = 150%
; external_perimeter_acceleration = 0
; external_perimeter_cut_corners = 0%
; external_perimeter_extrusion_spacing = 0.4
; external_perimeter_extrusion_width = 
; external_perimeter_fan_speed = -1
; external_perimeter_overlap = 100%
; external_perimeter_speed = 25
; external_perimeters_first = 0
; external_perimeters_hole = 1
; external_perimeters_nothole = 1
; external_perimeters_vase = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_odd_layers = 0
; extra_perimeters_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_fan_offset = 0%
; extruder_offset = 0x0
; extruder_temperature_offset = 0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_spacing = 
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; fan_kickstart = 0
; fan_percentage = 0
; fan_speedup_overhangs = 1
; fan_speedup_time = 0
; feature_gcode = 
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cooling_zone_pause = 0
; filament_cost = 25.4
; filament_custom_variables = ""
; filament_density = 1.24
; filament_diameter = 0.50022
; filament_dip_extraction_speed = 70
; filament_dip_insertion_speed = 33
; filament_enable_toolchange_part_fan = 0
; filament_enable_toolchange_temp = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_overlap = 100%
; filament_max_speed = 0
; filament_max_volumetric_speed = 15
; filament_max_wipe_tower_speed = 0
; filament_melt_zone_pause = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_length = 0
; filament_settings_id = Puredyne(New)
; filament_shrink = 100%
; filament_skinnydip_distance = 31
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_toolchange_part_fan_speed = 50
; filament_toolchange_temp = 200
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_use_fast_skinnydip = 0
; filament_use_skinnydip = 0
; filament_vendor = Generic
; filament_wipe_advanced_pigment = 0.5
; fill_angle = 45
; fill_angle_increment = 0
; fill_density = 15%
; fill_pattern = gyroid
; fill_smooth_distribution = 10%
; fill_smooth_width = 50%
; fill_top_flow_ratio = 100%
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_spacing = 
; first_layer_extrusion_width = 0.42
; first_layer_flow_ratio = 100%
; first_layer_height = 0.2
; first_layer_infill_speed = 20
; first_layer_min_speed = 20
; first_layer_size_compensation = -0.2
; first_layer_size_compensation_layers = 1
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 0
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 200%
; fuzzy_skin_thickness = 150%
; gap_fill_acceleration = 0
; gap_fill_enabled = 1
; gap_fill_flow_match_perimeter = 0%
; gap_fill_last = 0
; gap_fill_min_area = 100%
; gap_fill_overlap = 100%
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_filename_illegal_char = [<>:"/\\\\|?*]
; gcode_flavor = klipper
; gcode_label_objects = 1
; gcode_precision_e = 5
; gcode_precision_xyz = 3
; gcode_resolution = 0
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; hole_size_compensation = 0
; hole_size_threshold = 100
; hole_to_polyhole = 0
; hole_to_polyhole_threshold = 0.01
; hole_to_polyhole_twisted = 1
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_connection = connected
; infill_connection_bottom = connected
; infill_connection_solid = connected
; infill_connection_top = connected
; infill_dense = 0
; infill_dense_algo = autoenlarged
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_spacing = 
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = "0.20mm QUALITY @MK3";"Generic PLA";"Original Prusa i3 MK3S & MK3S+"
; init_z_rotate = 0
; interface_shells = 0
; ironing = 0
; ironing_acceleration = 0
; ironing_angle = -1
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 50%
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]\nSET_PRINT_STATS_INFO CURRENT_LAYER={layer_num + 1}
; layer_height = 0.2
; lift_min = 0
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_gcode_per_second = 1500
; max_layer_height = 0.25
; max_print_height = 35
; max_print_speed = 200
; max_speed_reduction = 90%
; max_volumetric_speed = 0
; milling_after_z = 200%
; milling_extra_size = 150%
; milling_post_process = 0
; milling_speed = 30
; milling_toolchange_end_gcode = 
; milling_toolchange_start_gcode = 
; min_fan_speed = 100
; min_layer_height = 0.07
; min_length = 0.035
; min_print_speed = 15
; min_skirt_length = 4
; min_width_top_surface = 100%
; mmu_segmented_region_max_width = 0
; model_precision = 0.0001
; no_perimeter_unsupported_algo = none
; notes = 
; nozzle_diameter = 0.4
; only_one_perimeter_first_layer = 0
; only_one_perimeter_top = 1
; only_one_perimeter_top_other_algo = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{filament_type[0]}_{printer_model}_{print_time}.gcode
; over_bridge_flow_ratio = 100%
; overhangs_acceleration = 0
; overhangs_reverse = 0
; overhangs_reverse_threshold = 250%
; overhangs_speed = 100%
; overhangs_width = 75%
; overhangs_width_speed = 55%
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_bonding = 0%
; perimeter_extruder = 1
; perimeter_extrusion_spacing = 0.4
; perimeter_extrusion_width = 
; perimeter_loop = 0
; perimeter_loop_seam = rear
; perimeter_overlap = 100%
; perimeter_round_corners = 0
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_custom_variables = wall_thickness_lines = 2\n
; print_extrusion_multiplier = 100%
; print_retract_length = -1
; print_retract_lift = -1
; print_settings_id = Puredyne (New)
; print_temperature = 0
; printer_custom_variables = 
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Puredyne(New)
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; remaining_times_type = m73
; resolution = 0.0125
; resolution_internal = 0.1
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_lift_first_layer = 0
; retract_lift_top = "All surfaces"
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_angle_cost = 50%
; seam_gap = 15%
; seam_position = cost
; seam_travel_cost = 50%
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_brim = 0
; skirt_distance = 2
; skirt_distance_from_brim = 1
; skirt_extrusion_width = 130%
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 15
; small_perimeter_max_length = 20
; small_perimeter_min_length = 6
; small_perimeter_speed = 25
; solid_fill_pattern = rectilineargapfill
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_spacing = 
; solid_infill_extrusion_width = 0.45
; solid_infill_overlap = 100%
; solid_infill_speed = 80
; solid_over_perimeters = 2
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0"
; start_gcode = SET_PRINT_STATS_INFO TOTAL_LAYER=[total_layer_count]\nM862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.10.1 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\n;M104 S{first_layer_temperature+extruder_temperature_offset} ; set extruder temp\n;M140 S[first_layer_bed_temperature] ; set bed temp\n;M190 S[first_layer_bed_temperature] ; wait for bed temp\n;M109 S{first_layer_temperature+extruder_temperature_offset} ; wait for extruder temp\nG28 W ; home all without mesh bed level\n; G80 ; mesh bed leveling\n;G1 Z0.2 F720\n;G1 Y-3 F1000 ; go outside print area\n;G92 E0\n;G1 X60 E9 F1000 ; intro line\n;G1 X100 E12.5 F1000 ; intro line\n;G92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; start_gcode_manual = 0
; support_material = 0
; support_material_acceleration = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0.2
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_contact_distance_type = filament
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_acceleration = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_fan_speed = -1
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 0
; template_custom_gcode = 
; thin_perimeters = 0%
; thin_perimeters_all = 20%
; thin_walls = 1
; thin_walls_acceleration = 0
; thin_walls_merge = 1
; thin_walls_min_width = 100%
; thin_walls_overlap = 80%
; thin_walls_speed = 100%
; threads = 10
; thumbnails = 32x32,400x400
; thumbnails_color = #018aff
; thumbnails_custom_color = 0
; thumbnails_end_file = 0
; thumbnails_format = PNG
; thumbnails_with_bed = 1
; time_cost = 0
; time_estimation_compensation = 100%
; time_start_gcode = 20
; time_toolchange = 30
; tool_name = ""
; toolchange_gcode = 
; top_fan_speed = -1
; top_fill_pattern = monotonic
; top_infill_extrusion_spacing = 
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_acceleration = 1500
; travel_deceleration_use_target = 1
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wipe = 1
; wipe_advanced = 0
; wipe_advanced_algo = linear
; wipe_advanced_multiplier = 60
; wipe_advanced_nozzle_melted_volume = 120
; wipe_extra_perimeter = 0
; wipe_inside_depth = 50%
; wipe_inside_end = 1
; wipe_inside_start = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_only_crossing = 1
; wipe_speed = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_inner_size_compensation = 0
; xy_size_compensation = 0
; z_offset = 0
; z_step = 0.005
; SuperSlicer_config = end
